export default function Head () {
  return (
    <>
      <title>CodewithRay</title>
      <meta content='width=device-width, initial-scale=1' name='viewport' />
      <meta name='description' content='Generated by create next app' />
      <link
        rel='icon'
        href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text x='50' y='55' font-size='60' text-anchor='middle' dominant-baseline='middle' font-family='monospace'>&lt;/&gt;</text></svg>"
      />
    </>
  )
}
